### ISSUE TITLE
could not broadcast input array from shape (200,2) into shape (1,2)

### ISSUE THREAD

**Issue by ZijianWu1121** [antonilo/rl_locomotion#6]
HI, I have use the follow command to test this proj but it runs error. What's the problem?

$ python raisimGymTorch/env/envs/rsg_a1_task/runner.py --name random --exptid 1 --loadid 0001 --overwrite --debug

Traceback (most recent call last):
  File "raisimGymTorch/env/envs/rsg_a1_task/runner.py", line 135, in <module>
    env.load_scaling(os.path.join(task_path, "../../../../data/rsg_a1_task/base_policy"),
  File "~/raisim/raisim_workspace/raisimLib/raisimGymTorch/raisimGymTorch/env/RaisimGymVecEnv.py", line 74, in load_scaling
    processed_mean[:,start:end] = g1_mean
ValueError: could not broadcast input array from shape (200,2) into shape (1,2)

**Comment by ZijianWu1121** [comment]
I have solved the problem. Debug mode should not be used
